export const FETCH_SONGS_START    = 'FETCH_SONGS_START';
export const FETCH_SONGS_SUCCESS  = 'FETCH_SONGS_SUCCESS';
export const FETCH_SONGS_ERROR    = 'FETCH_SONGS_ERROR';
export const SHOW_MORE_SONGS      = 'SHOW_MORE_SONGS';
export const TOGGLE_SONG_ORDERING = 'TOGGLE_SONG_ORDERING';
